CREATE TABLE CLIENTE (
    ID      INT             NOT NULL    AUTO_INCREMENT      PRIMARY KEY,
    NOME    VARCHAR(100)    NOT NULL
);

CREATE TABLE CONTASPAG (
    ID          INT             NOT NULL    AUTO_INCREMENT      PRIMARY KEY,
    DATA        DATE            NOT NULL,
    DATA_EXP    DATE            NOT NULL,
    IDCLIENTE    INT,
    VALOR       DECIMAL(12, 2)
);

ALTER TABLE CONTASPAG ADD CONSTRAINT FK_CONTASPAG_CLIENTE FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(ID);

INSERT INTO CLIENTE(NOME) VALUES ("Carol");
INSERT INTO CONTASPAG(DATA, DATA_EXP, IDCLIENTE, VALOR) VALUES ("2006/08/18", "2006/09/18", 1, 199.90);
